# Generated by Django 5.0.6 on 2024-07-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MssEmployees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_number', models.IntegerField()),
                ('employee_age', models.IntegerField()),
            ],
        ),
    ]
