# Generated by Django 5.0.6 on 2024-07-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MssEmployees', '0002_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_role', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('work_roles', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('years_of_experience', models.IntegerField(max_length=100)),
                ('employee_num', models.IntegerField(max_length=100)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MssEmployees.roles')),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MssEmployees.roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MssEmployees.user')),
            ],
        ),
    ]
